- name: "Configure Linux Distribution"
  hosts: localhost

  tasks:
    - name: "Set dnf defaultyes to True"
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: 'defaultyes='
        line: defaultyes=True
