- name: "Configure GNOME applications and shortcuts"
  hosts: localhost

  tasks:
    - name: "Configure '<Super>Return' To Open 'alacritty'"
      args:
        executable: /bin/bash
      shell: |
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "'Terminal'"
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "'<Super>Return'"
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "'alacritty'"

    - name: "Set Previously Configured Custom Key Bindings"
      args:
        executable: /bin/bash
      shell: # Add a new entry for each new custom setting with 'customX' with X being the next number
        gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

    - name: "Set '<Shift><Super>q' To Close Current Window"
      args:
        executable: /bin/bash
      shell: gsettings set org.gnome.desktop.wm.keybindings close "['<Shift><Super>q']"

    - name: "Remove 'totem' - Video Player"
      become: true
      dnf:
        state: absent
        name:
          - totem

    - name: "Remove 'gedit' - Text Editor"
      become: true
      dnf:
        state: absent
        name:
          - gedit

    - name: "Install 'gnome-tweaks'"
      become: true
      dnf:
        state: present
        name:
          - gnome-tweaks

    - name: "Install 'gnome-extensions-app'"
      community.general.flatpak:
        name: org.gnome.Extensions
        state: present
        method: user

    - name: "Install 'Text Editor'"
      community.general.flatpak:
        name: org.gnome.TextEditor
        state: present
        method: user
