- name: "Configure GNOME applications and shortcuts"
  hosts: localhost

  tasks:
    - name: "Configure '<Super>Return' To Open 'alacritty'"
      args:
        executable: /bin/bash
      shell: |
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "'Terminal'"
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "'<Super>Return'"
        gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "'alacritty'"
        gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

    - name: "Set '<Shift><Super>q' To Close Current Window"
      args:
        executable: /bin/bash
      shell: gsettings set org.gnome.desktop.wm.keybindings close "['<Shift><Super>q']"

    - name: "Disable Hot Corner"
      args:
        executable: /bin/bash
      shell: gsettings set org.gnome.desktop.interface enable-hot-corners false

    - name: "Disable Animations"
      args:
        executable: /bin/bash
      shell: gsettings set org.gnome.desktop.interface enable-animations false

    - name: "Set Clock-format to '12h'"
      args:
        executable: /bin/bash
      shell: |
        gsettings set org.gnome.desktop.interface clock-format '12h'
        gsettings set org.gtk.Settings.FileChooser clock-format '12h'
        gsettings set org.gtk.gtk4.Settings.FileChooser clock-format '12h'

    - name: "Set Favorite Apps"
      args:
        executable: /bin/bash
      shell: gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'org.gnome.TextEditor.desktop', 'org.mozilla.firefox.desktop', 'jetbrains-idea.desktop', 'jetbrains-pycharm.desktop', 'jetbrains-webstorm.desktop', 'io.bassi.Amberol.desktop', 'steam.desktop', 'com.discordapp.Discord.desktop', 'org.telegram.desktop.desktop', 'com.microsoft.Teams.desktop', 'com.teamspeak.TeamSpeak.desktop']"

    - name: "Disable All Window Buttons"
      args:
        executable: /bin/bash
      shell: gsettings set org.gnome.desktop.wm.preferences button-layout ""

    - name: "Remove 'totem' - Video Player"
      become: true
      dnf:
        state: absent
        name:
          - totem

    - name: "Remove 'gedit' - Text Editor"
      become: true
      dnf:
        state: absent
        name:
          - gedit

    - name: "Install 'gnome-tweaks'"
      become: true
      dnf:
        state: present
        name:
          - gnome-tweaks
