- name: "Install Terminal Applications"
  hosts: localhost

  tasks:
    - name: "Install 'bat' - Modern 'cat' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - bat

    - name: "Install 'dtrx' - User Friendly Archive Extraction"
      become: yes
      pip:
        state: present
        name:
          - dtrx

#    - name: 'Install dust - Modern du alternative'
#      become: yes
#      args:
#        executable: /bin/bash
#      shell: |
#        VERSION="v0.8.3"
#        FILE_NAME="dust-$VERSION-x86_64-unknown-linux-musl"
#        FILE_NAME_FULL="${FILE_NAME}.tar.gz"
#        curl -s https://api.github.com/repos/bootandy/dust/releases/latest \
#          | grep "browser_download_url.*$FILE_NAME_FULL" \
#          | cut -d : -f 2,3 \
#          | tr -d \" \
#          | wget -qi -
#        tar -xvzf "$FILE_NAME_FULL" "$FILE_NAME/dust"
#        mv "$FILE_NAME/dust" /usr/local/bin/
#        rm -rf "$FILE_NAME/dust"

    - name: "Install 'lsd' - Modern 'ls' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - lsd

    - name: "Install 'fd-find' - Modern 'find' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - fd-find

    - name: "Install 'neofetch' - System Info"
      become: yes
      dnf:
        state: present
        name:
          - neofetch

    - name: "Install 'procs' - Modern 'ps' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - procs

    - name: "Install 'ripgrep' - Modern 'grep' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - ripgrep

    - name: "Install 'tokei'"
      become: yes
      dnf:
        state: present
        name:
          - tokei

    - name: "Remove 'vim'"
      become: yes
      dnf:
        state: absent
        name:
          - vim

    - name: "Install 'NeoVim'"
      become: yes
      dnf:
        state: present
        name:
          - neovim
          - python3-neovim
