- name: "Install Terminal Applications"
  hosts: localhost

  tasks:
    - name: "Install 'bat' - Modern 'cat' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - bat

    - name: "Install 'bpytop' - Interactive System Monitor"
      become: yes
      dnf:
        state: present
        name:
          - bpytop

    - name: "Install 'dtrx' - User Friendly Archive Extraction"
      become: yes
      pip:
        state: present
        name:
          - dtrx

    - name: "Install 'exa' - Modern 'ls' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - exa

    - name: "Install 'fd-find' - Modern 'find' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - fd-find

    - name: "Install 'neofetch' - System Info"
      become: yes
      dnf:
        state: present
        name:
          - neofetch

    - name: "Install 'procs' - Modern 'ps' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - procs

    - name: "Install 'ripgrep' - Modern 'grep' Alternative"
      become: yes
      dnf:
        state: present
        name:
          - ripgrep

    - name: "Install 'tokei'"
      become: yes
      dnf:
        state: present
        name:
          - tokei

    - name: "Install 'wormhole' - Easy File Transfer"
      become: yes
      community.general.snap:
        state: present
        name:
          - wormhole

    - name: "Install 'vim' - Text Editor"
      become: yes
      dnf:
        state: present
        name:
          - vim
