- name: "Install Graphical Applications"
  hosts: localhost

  vars:
    custom_programs: "~/apps/programs"

  tasks:
    - name: "Remove 'eog'"
      become: true
      dnf:
        state: absent
        name:
          - eog

    - name: "Remove 'Firefox'"
      become: yes
      dnf:
        state: absent
        name:
          - firefox

    - name: "Remove 'Gedit'"
      become: true
      dnf:
        state: absent
        name:
          - gedit

    - name: "Remove 'Totem'"
      become: true
      dnf:
        state: absent
        name:
          - totem

    - name: "Install 'JetBrains Toolbox App'"
      args:
        executable: /bin/bash
      shell: |
        # Source: https://gist.github.com/abn/022c5f9eae491687a766f25bd8322fc0
        # Reference: https://github.com/nagygergo/jetbrains-toolbox-install/blob/master/jetbrains-toolbox.sh

        # Note that we grep for linux here, if you are using this on mac/windows please see json output
        TOOLBOX_URL=$(curl --silent 'https://data.services.jetbrains.com//products/releases?code=TBA&latest=true&type=release' \
            -H 'Origin: https://www.jetbrains.com' \
            -H 'Accept-Encoding: gzip, deflate, br' \
            -H 'Accept-Language: en-US,en;q=0.8' \
            -H 'Accept: application/json, text/javascript, */*; q=0.01' \
            -H 'Referer: https://www.jetbrains.com/toolbox/download/' \
            -H 'Connection: keep-alive' \
            -H 'DNT: 1' \
            --compressed \
          | grep -Po '"linux":.*?[^\\]",' \
          | awk -F ':' '{print $3,":"$4}'| sed 's/[", ]//g')

        install -d ${HOME}/bin
        curl -sL ${TOOLBOX_URL} | tar xvz --directory=${HOME}/bin --strip-components=1

        $HOME/bin/jetbrains-toolbox

    - name: "Install '1Password'"
      community.general.flatpak:
        name: https://downloads.1password.com/linux/flatpak/1Password.flatpakref
        method: user
        state: present

    - name: "Install 'Alacritty'"
      become: yes
      dnf:
        state: present
        name:
          - alacritty

    - name: "Install 'Amberol'"
      community.general.flatpak:
        name: io.bassi.Amberol
        method: user
        state: present

    - name: "Install 'Audacity'"
      community.general.flatpak:
        name: org.audacityteam.Audacity
        method: user
        state: present

    - name: "Install 'Discord'"
      community.general.flatpak:
        name: com.discordapp.Discord
        method: user
        state: present

    - name: "Install 'Extensions'"
      community.general.flatpak:
        name: org.gnome.Extensions
        method: user
        state: present

    - name: "Install 'Firefox' (flatpak)"
      community.general.flatpak:
        name: org.mozilla.firefox
        state: present
        method: user

    - name: "Install 'Flatseal'"
      community.general.flatpak:
        name: com.github.tchx84.Flatseal
        method: user
        state: present

    - name: "Install 'GNOME Text Editor'"
      community.general.flatpak:
        name: org.gnome.TextEditor
        method: user
        state: present

    - name: "Install 'Hexchat'"
      community.general.flatpak:
        name: io.github.Hexchat
        method: user
        state: present

    - name: "Install 'loupe' - Image Viewer"
      community.general.flatpak:
        name: org.gnome.Loupe
        state: present
        method: user

    - name: "Install 'mpv'"
      community.general.flatpak:
        name: io.mpv.Mpv
        method: user
        state: present

    - name: "Install 'Steam'"
      become: yes
      dnf:
        state: present
        name:
          - steam

    - name: "Install 'Spotify'"
      community.general.flatpak:
        name: com.spotify.Client
        method: user
        state: present

    - name: "Install 'Teamspeak'"
      community.general.flatpak:
        name: com.teamspeak.TeamSpeak
        method: user
        state: present

    - name: "Install 'Telegram Messenger'"
      community.general.flatpak:
        name: org.telegram.desktop
        method: user
        state: present
