- name: "Install Shell & Dotfiles"
  hosts: localhost

  vars:
    starship_installer: "installer-starship.sh"
    dotfiles_repository: "https://github.com/trin94/dotfiles.git"

  tasks:
    - name: "Install Fish Shell"
      become: yes
      dnf:
        state: present
        name:
          - fish

    - name: "Download Starship Installer"
      become: true
      get_url:
        url: https://starship.rs/install.sh
        dest: "~/{{ starship_installer }}"

    - name: "Run Starship Installer"
      become: true
      shell: |
        cd ~
        sh {{ starship_installer }} -y

    - name: "Clone & Setup Dotfiles"
      shell: |
        cd ~
        echo 'alias config="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"' >> $HOME/.bashrc
        source ~/.bashrc
        echo ".dotfiles.git" >> .gitignore
        git clone --bare {{ dotfiles_repository }} $HOME/.dotfiles.git
        config checkout -f
        config config --local status.showUntrackedFiles no

    - name: "Ensure Vim Autoload Directory Exists"
      file:
        state: directory
        path: ~/.local/share/nvim/site/autoload

    - name: "Install Vim-Plug"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.local/share/nvim/site/autoload/plug.vim

    - name: "Install Vim-Plugins"
      shell: |
        nvim +PlugInstall +qall
