- name: "Add Flatpak Remotes"
  hosts: localhost

  tasks:
    - name: "Install flatpak"
      become: true
      apt:
        pkg:
          - flatpak

    - name: "Add Flatpak Remote 'flathub'"
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user