- name: "Install Terminal Applications"
  hosts: localhost

  tasks:
    - name: "Install Terminal Applications"
      become: true
      community.general.pacman:
        update_cache: yes
        state: present
        name:
          - atool                     # Extraction tool
          - bat                       # Alternative for cat
          - bpytop                    # Task manager
          - exa                       # Alternative for fd
          - fd                        # Alternative for find
          - neofetch                  # Quickly show system info
          - procs                     # Alternative for ps
          - ripgrep                   # Alternative for grep
          - tldr                      # Simple examples for terminal applications
          - tokei                     # Programming language statistics
          - vim                       # Terminal text editor
